development:
  adapter:  postgresql
  host:     localhost
  database: band-aider_development
  username: band-aider
  password:

test:
  adapter:  postgresql
  host:     localhost
  database: band-aider_test
  username: band-aider
  password:
